#undef LEFT_ANSI_SIX_ONE
#undef LEFT_ANSI_SIX_TWO
#undef LEFT_ANSI_SIX_THREE
#undef RIGHT_ANSI_SIX_ONE
#undef RIGHT_ANSI_SIX_TWO
#undef RIGHT_ANSI_SIX_THREE
#define LEFT_ANSI_SIX_ONE KC_NO,
#define LEFT_ANSI_SIX_TWO KC_NO,
#define LEFT_ANSI_SIX_THREE KC_NO,
#define RIGHT_ANSI_SIX_ONE KC_NO,
#define RIGHT_ANSI_SIX_TWO KC_NO,
#define RIGHT_ANSI_SIX_THREE KC_NO,

#undef BOTTOM_ROW_40P_ANSI
#define BOTTOM_ROW_40P_ANSI LT(LAYER_ID_40P_MEDIA, KC_ESC), LT(LAYER_ID_40P_NAVIGATION, KC_SPACE), LT(LAYER_ID_40P_MOUSE, KC_TAB), F0P_THUMB_MID_NONES LT(LAYER_ID_SYMBOLS, KC_ENT), LT(LAYER_ID_NUMBERS, KC_BSPC), LT(LAYER_ID_BIG_FUN, KC_DEL)


// Remap Y to N on base layer
#undef KEY_B2
#define KEY_B2 KC_N

// Swap Custom and Symbol activation
#undef KEY_B1
#undef KEY_B4
#define KEY_B1 LT(LAYER_ID_CUSTOM, KC_E)
#define KEY_B4 LT(LAYER_ID_SYMBOLS, KC_O)

// Symbol layer
#define KSYM_T1 KC_EXLM
#define KSYM_T2 S(KC_2)
#define KSYM_T3 KC_NUHS
#define KSYM_T4 KC_LCBR
#define KSYM_B1 KC_DLR
#define KSYM_B2 KC_PERC
#define KSYM_B3 KC_CIRC
#define KSYM_B4 KC_COLN

// Custom layer
#define KCUS_T1 KC_NO
#define KCUS_T2 KC_WFWD
#define KCUS_T3 KC_INS
#define KCUS_T4 KC_RSFT
#define KCUS_B1 KC_TRNS
#define KCUS_B2 KC_WBAK
#define KCUS_B3 KC_PSCR
#define KCUS_B4 KC_RCTL

// Parenthicals layer
#define KPAR_T1 KC_TRNS
#define KPAR_T2 KC_RPRN
#define KPAR_T3 KC_LPRN
#define KPAR_T4 KC_RCBR
#define KPAR_B1 KC_NO
#define KPAR_B2 KC_RBRC
#define KPAR_B3 KC_LBRC
#define KPAR_B4 KC_LCBR
