/// UK Layout changes
// KC_BSLS -> KC_NUBS
// KC_HASH -> KC_NUHS
// KC_PIPE -> S(KC_NUBS)

/// Ardux std layer changes
#ifdef ARDUX_SIZE_STD

#define ARDUX_STD_LAYER_CUS_LEFT \
STD_LEADING_NONES \
KCUS_T4,            KCUS_T3,          KCUS_T2,           KCUS_T1,          \
STD_BETWEEN_ROW_ONE_TWO_NONES \
KCUS_B4,          KCUS_B3,          KCUS_B2,          KCUS_B1           \
STD_TRAILING_NONES

#define ARDUX_STD_LAYER_PAR_LEFT \
STD_LEADING_NONES \
KPAR_T4,          KPAR_T3,          KPAR_T2,          KPAR_T1,          \
STD_BETWEEN_ROW_ONE_TWO_NONES \
KPAR_B4,          KPAR_B3,          KPAR_B2,          KPAR_B1             \
STD_TRAILING_NONES

#define ARDUX_STD_LAYER_SYM_LEFT \
STD_LEADING_NONES \
KSYM_T4,           KSYM_T3,          KSYM_T2,          KSYM_T1,          \
STD_BETWEEN_ROW_ONE_TWO_NONES \
KSYM_B4,           KSYM_B3,          KSYM_B2,          KSYM_B1           \
STD_TRAILING_NONES

#endif

/// Ardux 40p layer changes
#ifdef ARDUX_SIZE_40P

#define ARDUX_BIG_LAYER_CUS_LEFT_THUMBS KC_NO, KC_NO, KC_NO
#define ARDUX_BIG_LAYER_CUS_LEFT \
BIG_LEADING_NONES \
KCUS_T4,            KCUS_T3,          KCUS_T2,           KCUS_T1,          KC_NO,            \
BIG_BETWEEN_ROW_ONE_TWO_NONES \
KCUS_B4,          KCUS_B3,          KCUS_B2,          KCUS_B1,          KC_NO,            \
BIG_BETWEEN_ROW_TWO_THREE_NONES \
KC_NO,            KC_NO,            KC_NO,            KC_NO,            KC_NO,            \
BIG_BETWEEN_ROW_THREE_THUMBS_NONES \
ARDUX_BIG_LAYER_CUS_LEFT_THUMBS \
BIG_TRAILING_NONES

#define ARDUX_BIG_LAYER_PAR_LEFT_LEFT KC_NO, KC_NO, KC_NO
#define ARDUX_BIG_LAYER_PAR_LEFT \
BIG_LEADING_NONES \
KPAR_T4,          KPAR_T3,          KPAR_T2,          KPAR_T1,          KC_NO,            \
BIG_BETWEEN_ROW_ONE_TWO_NONES \
KPAR_B4,          KPAR_B3,          KPAR_B2,          KPAR_B1,            KC_NO,            \
BIG_BETWEEN_ROW_TWO_THREE_NONES \
KC_NO,            KC_NO,            KC_NO,            KC_NO,            KC_NO,            \
BIG_BETWEEN_ROW_THREE_THUMBS_NONES \
ARDUX_BIG_LAYER_PAR_LEFT_LEFT \
BIG_TRAILING_NONES

#define ARDUX_BIG_LAYER_BASE_LEFT_THUMBS MO(LAYER_ID_NAVIGATION), KC_SPC, KC_ENT
#define ARDUX_MINUS TD(TD_40P)
#define ARDUX_BIG_LAYER_BASE_LEFT \
BIG_LEADING_NONES \
KEY_T4,           KEY_T3,           KEY_T2,           KEY_T1,           ARDUX_MINUS,     \
BIG_BETWEEN_ROW_ONE_TWO_NONES \
KEY_B4,           KEY_B3,           KEY_B2,           KEY_B1,           OSM_SHIFT,        \
BIG_BETWEEN_ROW_TWO_THREE_NONES \
LALT_T(OSM_CTRL), KC_AT,            KC_DEL,           KC_EQL,           KC_TAB,           \
BIG_BETWEEN_ROW_THREE_THUMBS_NONES \
ARDUX_BIG_LAYER_BASE_LEFT_THUMBS \
BIG_TRAILING_NONES

#endif


/// Miryoku 40P
#define ARDUX_40P_LAYER_ANSI \
F0P_LEADING_NONES \
LEFT_ANSI_SIX_ONE LEFT_NUMBERS, KC_W, KC_E, LEFT_PARENTHETICALS, TD(TD_ARDUX_LEFT),    F0P_ROW_ONE_MID_NONES     TD(TD_ARDUX_RIGHT), RIGHT_PARENTHETICALS, KC_I, KC_O, RIGHT_NUMBERS, RIGHT_ANSI_SIX_ONE \
F0P_BETWEEN_ROW_ONE_TWO_NONES \
LEFT_ANSI_SIX_TWO LGUI_T(KC_A), LALT_T(KC_S), LCTL_T(KC_D), LSFT_T(KC_F), KC_G,    F0P_ROW_TWO_MID_NONES    KC_H, LSFT_T(KC_J), LCTL_T(KC_K), LALT_T(KC_L), LGUI_T(KC_QUOT), RIGHT_ANSI_SIX_TWO \
F0P_BETWEEN_ROW_TWO_THREE_NONES \
LEFT_ANSI_SIX_THREE LT(LAYER_ID_40P_BUTTON, KC_Z), KC_X, KC_C,  KC_V, KC_B,    F0P_ROW_THREE_MID_NONES    KC_N, KC_M, KC_COMMA, KC_DOT, LT(LAYER_ID_40P_BUTTON, KC_SLSH), RIGHT_ANSI_SIX_THREE \
F0P_BETWEEN_ROW_THREE_THUMBS_NONES \
BOTTOM_ROW_40P_ANSI \
F0P_TRAILING_NONES

#define LEFT_FUNCTION_SIX_ONE KC_NO,
#define LEFT_FUNCTION_SIX_TWO KC_NO,
#define LEFT_FUNCTION_SIX_THREE KC_NO,
#define RIGHT_FUNCTION_SIX_ONE KC_NO,
#define RIGHT_FUNCTION_SIX_TWO KC_NO,
#define RIGHT_FUNCTION_SIX_THREE KC_NO,
#define BOTTOM_ROW_40P_FUN KC_APP, KC_SPC, KC_TAB,    F0P_THUMB_MID_NONES    KC_NO, KC_NO, KC_NO
// Reuse the existing big function layer
#define ARDUX_BIG_LAYER_BIG_FUN_LEFT \
F0P_LEADING_NONES \
LEFT_FUNCTION_SIX_ONE KC_F10, KC_F3, KC_F2, KC_F1, KC_PSCR,    F0P_ROW_ONE_MID_NONES    KC_NO, KC_NO, KC_NO, KC_NO, RESET, RIGHT_FUNCTION_SIX_ONE \
F0P_BETWEEN_ROW_ONE_TWO_NONES \
LEFT_FUNCTION_SIX_TWO KC_F11, KC_F6, KC_F5, KC_F4, KC_SLCK,    F0P_ROW_TWO_MID_NONES    KC_NO, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, RIGHT_FUNCTION_SIX_TWO \
F0P_BETWEEN_ROW_TWO_THREE_NONES \
LEFT_FUNCTION_SIX_THREE KC_F12, KC_F9, KC_F8, KC_F7, KC_PAUS,    F0P_ROW_THREE_MID_NONES    KC_NO, KC_NO, KC_NO, KC_ALGR, KC_NO, RIGHT_FUNCTION_SIX_THREE \
F0P_BETWEEN_ROW_THREE_THUMBS_NONES \
BOTTOM_ROW_40P_FUN \
F0P_TRAILING_NONES

#define LEFT_NAV_SIX_ONE KC_NO,
#define LEFT_NAV_SIX_TWO KC_NO,
#define LEFT_NAV_SIX_THREE KC_NO,
#define RIGHT_NAV_SIX_ONE KC_NO,
#define RIGHT_NAV_SIX_TWO KC_NO,
#define RIGHT_NAV_SIX_THREE KC_NO,
#define BOTTOM_ROW_40P_NAV KC_NO, KC_NO, KC_NO,    F0P_THUMB_MID_NONES    KC_ENT, KC_BSPC, KC_DEL
#define ARDUX_40P_LAYER_NAVIGATION \
F0P_LEADING_NONES \
LEFT_NAV_SIX_ONE RESET, KC_NO, KC_NO, KC_NO, KC_NO,    F0P_ROW_ONE_MID_NONES    C(KC_Y), C(KC_V), C(KC_C), C(KC_X), C(KC_Z), RIGHT_NAV_SIX_ONE \
F0P_BETWEEN_ROW_ONE_TWO_NONES \
LEFT_NAV_SIX_TWO KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_NO,    F0P_ROW_TWO_MID_NONES    KC_LEFT, KC_DOWN, KC_UP, KC_RIGHT, KC_CAPS, RIGHT_NAV_SIX_TWO \
F0P_BETWEEN_ROW_TWO_THREE_NONES \
LEFT_NAV_SIX_THREE KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,    F0P_ROW_THREE_MID_NONES    KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_INS, RIGHT_NAV_SIX_THREE \
F0P_BETWEEN_ROW_THREE_THUMBS_NONES \
BOTTOM_ROW_40P_NAV \
F0P_TRAILING_NONES

#define LEFT_SYM_SIX_ONE KC_NO,
#define LEFT_SYM_SIX_TWO KC_NO,
#define LEFT_SYM_SIX_THREE KC_NO,
#define RIGHT_SYM_SIX_ONE KC_NO,
#define RIGHT_SYM_SIX_TWO KC_NO,
#define RIGHT_SYM_SIX_THREE KC_NO,
#define BOTTOM_ROW_40P_SYM KC_LPRN, KC_RPRN, KC_UNDS,    F0P_THUMB_MID_NONES    KC_NO, KC_NO, KC_NO
// Reuse the existing symbol layer
#define ARDUX_BIG_LAYER_SYM_LEFT \
F0P_LEADING_NONES \
LEFT_SYM_SIX_ONE KSYM_T4, KSYM_T3, KSYM_T2, KSYM_T1, KC_RCBR,    F0P_ROW_ONE_MID_NONES    KC_NO, KC_NO, KC_NO, KC_NO, RESET, RIGHT_SYM_SIX_ONE \
F0P_BETWEEN_ROW_ONE_TWO_NONES \
LEFT_SYM_SIX_TWO KSYM_B4, KSYM_B3, KSYM_B2, KSYM_B1, KC_PLUS,    F0P_ROW_TWO_MID_NONES    KC_NO, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, RIGHT_SYM_SIX_TWO \
F0P_BETWEEN_ROW_TWO_THREE_NONES \
LEFT_SYM_SIX_THREE S(KC_NUHS), KC_LPRN, KC_ASTR, KC_AMPR, S(KC_NUBS),    F0P_ROW_THREE_MID_NONES    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RIGHT_SYM_SIX_THREE \
F0P_BETWEEN_ROW_THREE_THUMBS_NONES \
BOTTOM_ROW_40P_SYM \
F0P_TRAILING_NONES

#define LEFT_NUM_SIX_ONE KC_NO,
#define LEFT_NUM_SIX_TWO KC_NO,
#define LEFT_NUM_SIX_THREE KC_NO,
#define RIGHT_NUM_SIX_ONE KC_NO,
#define RIGHT_NUM_SIX_TWO KC_NO,
#define RIGHT_NUM_SIX_THREE KC_NO,
#define BOTTOM_ROW_40P_NUM KC_DOT, KC_0, KC_MINS,    F0P_THUMB_MID_NONES    KC_NO, KC_NO, KC_NO
// Reuse the existing number layer
#define ARDUX_BIG_LAYER_NUM_LEFT \
F0P_LEADING_NONES \
LEFT_NUM_SIX_ONE KC_LBRC, KNUM_T3, KNUM_T2, KNUM_T1, KC_RBRC,    F0P_ROW_ONE_MID_NONES    KC_NO, KC_NO, KC_NO, KC_NO, RESET, RIGHT_NUM_SIX_ONE \
F0P_BETWEEN_ROW_ONE_TWO_NONES \
LEFT_NUM_SIX_TWO KC_SCLN, KNUM_B3, KNUM_B2, KNUM_B1, KC_EQL,    F0P_ROW_TWO_MID_NONES    KC_NO, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, RIGHT_NUM_SIX_TWO \
F0P_BETWEEN_ROW_TWO_THREE_NONES \
LEFT_NUM_SIX_THREE KC_GRV, KC_9, KC_8, KC_7, KC_NUBS,    F0P_ROW_THREE_MID_NONES    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RIGHT_NUM_SIX_THREE \
F0P_BETWEEN_ROW_THREE_THUMBS_NONES \
BOTTOM_ROW_40P_NUM \
F0P_TRAILING_NONES

#define LEFT_MEDIA_SIX_ONE KC_NO,
#define LEFT_MEDIA_SIX_TWO KC_NO,
#define LEFT_MEDIA_SIX_THREE KC_NO,
#define RIGHT_MEDIA_SIX_ONE KC_NO,
#define RIGHT_MEDIA_SIX_TWO KC_NO,
#define RIGHT_MEDIA_SIX_THREE KC_NO,
#define BOTTOM_ROW_40P_MEDIA KC_NO, KC_NO, KC_NO,    F0P_THUMB_MID_NONES    KC_MSTP, KC_MPLY, KC_MUTE
#define ARDUX_40P_LAYER_MEDIA \
F0P_LEADING_NONES \
LEFT_MEDIA_SIX_ONE RESET, KC_NO, KC_NO, KC_NO, KC_NO,    F0P_ROW_ONE_MID_NONES    RGB_TOG, RGB_MOD, RGB_HUI, RGB_SAI, RGB_VAI, RIGHT_MEDIA_SIX_ONE \
F0P_BETWEEN_ROW_ONE_TWO_NONES \
LEFT_MEDIA_SIX_TWO KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_NO,    F0P_ROW_TWO_MID_NONES    KC_MPRV, KC_VOLD, KC_VOLU, KC_MNXT, KC_NO, RIGHT_MEDIA_SIX_TWO \
F0P_BETWEEN_ROW_TWO_THREE_NONES \
LEFT_MEDIA_SIX_THREE KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,    F0P_ROW_THREE_MID_NONES    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RIGHT_MEDIA_SIX_THREE \
F0P_BETWEEN_ROW_THREE_THUMBS_NONES \
BOTTOM_ROW_40P_MEDIA \
F0P_TRAILING_NONES

#define LEFT_MOUSE_SIX_ONE KC_NO,
#define LEFT_MOUSE_SIX_TWO KC_NO,
#define LEFT_MOUSE_SIX_THREE KC_NO,
#define RIGHT_MOUSE_SIX_ONE KC_NO,
#define RIGHT_MOUSE_SIX_TWO KC_NO,
#define RIGHT_MOUSE_SIX_THREE KC_NO,
#define BOTTOM_ROW_40P_MOUSE KC_NO, KC_NO, KC_NO,    F0P_THUMB_MID_NONES    KC_BTN1, KC_BTN3, KC_BTN2
#define ARDUX_40P_LAYER_MOUSE \
F0P_LEADING_NONES \
LEFT_MOUSE_SIX_ONE RESET, KC_NO, KC_NO, KC_NO, KC_NO,    F0P_ROW_ONE_MID_NONES    C(KC_Y), C(KC_V), C(KC_C), C(KC_X), C(KC_Z), RIGHT_MOUSE_SIX_ONE \
F0P_BETWEEN_ROW_ONE_TWO_NONES \
LEFT_MOUSE_SIX_TWO KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_NO,    F0P_ROW_TWO_MID_NONES    KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, KC_NO, RIGHT_MOUSE_SIX_TWO \
F0P_BETWEEN_ROW_TWO_THREE_NONES \
LEFT_MOUSE_SIX_THREE KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,    F0P_ROW_THREE_MID_NONES    KC_WH_L, KC_WH_D, KC_WH_U, KC_WH_R, KC_NO, RIGHT_MOUSE_SIX_THREE \
F0P_BETWEEN_ROW_THREE_THUMBS_NONES \
BOTTOM_ROW_40P_MOUSE \
F0P_TRAILING_NONES

#define LEFT_BUTTON_SIX_ONE KC_NO,
#define LEFT_BUTTON_SIX_TWO KC_NO,
#define LEFT_BUTTON_SIX_THREE KC_NO,
#define RIGHT_BUTTON_SIX_ONE KC_NO,
#define RIGHT_BUTTON_SIX_TWO KC_NO,
#define RIGHT_BUTTON_SIX_THREE KC_NO,
#define BOTTOM_ROW_40P_BUTTON KC_BTN2, KC_BTN3, KC_BTN1,    F0P_THUMB_MID_NONES    KC_BTN1, KC_BTN3, KC_BTN2
#define ARDUX_40P_LAYER_BUTTON \
F0P_LEADING_NONES \
LEFT_BUTTON_SIX_ONE C(KC_Z), C(KC_X), C(KC_C), C(KC_V), C(KC_Y),    F0P_ROW_ONE_MID_NONES    C(KC_Y), C(KC_V), C(KC_C), C(KC_X), C(KC_Z), RIGHT_BUTTON_SIX_ONE \
F0P_BETWEEN_ROW_ONE_TWO_NONES \
LEFT_BUTTON_SIX_TWO KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_TRNS,    F0P_ROW_TWO_MID_NONES    KC_TRNS, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, RIGHT_BUTTON_SIX_TWO \
F0P_BETWEEN_ROW_TWO_THREE_NONES \
LEFT_BUTTON_SIX_THREE C(KC_Z), C(KC_X), C(KC_C), C(KC_V), C(KC_Y),    F0P_ROW_THREE_MID_NONES    C(KC_Y), C(KC_V), C(KC_C), C(KC_X), C(KC_Z), RIGHT_BUTTON_SIX_THREE \
F0P_BETWEEN_ROW_THREE_THUMBS_NONES \
BOTTOM_ROW_40P_BUTTON \
F0P_TRAILING_NONES
