#undef LEFT_ANSI_SIX_ONE
#undef LEFT_ANSI_SIX_TWO
#undef LEFT_ANSI_SIX_THREE
#undef RIGHT_ANSI_SIX_ONE
#undef RIGHT_ANSI_SIX_TWO
#undef RIGHT_ANSI_SIX_THREE
#define LEFT_ANSI_SIX_ONE KC_NO,
#define LEFT_ANSI_SIX_TWO KC_NO,
#define LEFT_ANSI_SIX_THREE KC_NO,
#define RIGHT_ANSI_SIX_ONE KC_NO,
#define RIGHT_ANSI_SIX_TWO KC_NO,
#define RIGHT_ANSI_SIX_THREE KC_NO,

#undef BOTTOM_ROW_40P_ANSI
#define BOTTOM_ROW_40P_ANSI LT(LAYER_ID_40P_MEDIA, KC_ESC), LT(LAYER_ID_40P_NAVIGATION, KC_SPACE), LT(LAYER_ID_40P_MOUSE, KC_TAB), F0P_THUMB_MID_NONES LT(LAYER_ID_40P_SYM, KC_ENT), LT(LAYER_ID_40P_NUM, KC_BSPC), LT(LAYER_ID_40P_FUNCTION, KC_DEL)
