// Miryoku Extra 40% ARDUX layer IDs
#define LAYER_ID_40P_MEDIA (LAYER_ID_BIG_FUN + 1)
#define LAYER_ID_40P_SYM (LAYER_ID_BIG_FUN + 2)
#define LAYER_ID_40P_NUM (LAYER_ID_BIG_FUN + 3)
#define LAYER_ID_40P_MOUSE (LAYER_ID_BIG_FUN + 4)
#define LAYER_ID_40P_BUTTON (LAYER_ID_BIG_FUN + 5)
